# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount
include: ['_pages/', 'images']

# configuration required for some pages

title: Kuba Alimbekov
author: Kuba
email: alimbeko@zoho.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

#google_analytics:
#  account: UA-27240426-1


github:
  username: alimbeko

# disqus:
#   id: disqusid
